version: '3.7'

services:

  backend:
    build:
      context: ../../
      dockerfile: ci/dev/docker/backend/Dockerfile
    restart: on-failure
    volumes:
      - "../../app/backend/:/var/app"
    depends_on:
      - psql
    env_file:
      - docker/backend/docker-compose.env

  psql:
    image: postgres:13-alpine
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - "psql_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB}

networks:
  default: {}

volumes:
  psql_data: {}
