version: '3.7'

services:
  psql:
    image: postgres:13-alpine
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - "psql_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB}

volumes:
  psql_data: {}
